import {
  IArtist,
  IGenre,
  IMood,
  IPlaylist,
  IPrivacy,
  IRoom,
  ISong,
} from "@/types";
import { IMessageChat } from "@/types/room.type";

export const privacy: IPrivacy[] = [
  {
    value: "public",
    label: "Public",
    description: "Anyone will be able to listens to this track.",
  },
  {
    value: "private",
    label: "Private",
    description: "Only you will be able to listens to this track.",
  },
];

export const moods: IMood[] = [
  {
    id: "1",
    title: "Happy",
    description: "Description 1",
  },
  {
    id: "2",
    title: "Sad",
    description: "Description 2",
  },
  {
    id: "3",
    title: "Angry",
    description: "Description 3",
  },
  {
    id: "4",
    title: "Relaxed",
    description: "Description 4",
  },
  {
    id: "5",
    title: "Excited",
    description: "Description 5",
  },
  {
    id: "6",
    title: "Romantic",
    description: "Description 6",
  },
  {
    id: "7",
    title: "Energetic",
    description: "Description 7",
  },
  {
    id: "8",
    title: "Calm",
    description: "Description 8",
  },
  {
    id: "9",
    title: "Melancholic",
    description: "Description 9",
  },
  {
    id: "10",
    title: "Joyful",
    description: "Description 10",
  },
  {
    id: "11",
    title: "Nostalgic",
    description: "Description 11",
  },
  {
    id: "12",
    title: "Peaceful",
    description: "Description 12",
  },
  {
    id: "13",
    title: "Hopeful",
    description: "Description 13",
  },
];

export const genres: IGenre[] = [
  {
    id: "1",
    title: "Pop",
    description: "Description 1",
    color: "rgba(255, 99, 132, 0.8)",
    imagePath: "",
  },
  {
    id: "2",
    title: "Rock",
    description: "Description 2",
    color: "rgba(54, 162, 235, 0.8)",
    imagePath: "",
  },
  {
    id: "3",
    title: "Jazz",
    description: "Description 3",
    color: "rgba(255, 206, 86, 0.8)",
    imagePath: "",
  },
  {
    id: "4",
    title: "Classical",
    description: "Description 4",
    color: "rgba(75, 192, 192, 0.8)",
    imagePath: "",
  },
  {
    id: "5",
    title: "Hip-Hop",
    description: "Description 5",
    color: "rgba(153, 102, 255, 0.8)",
    imagePath: "",
  },
  {
    id: "6",
    title: "Electronic",
    description: "Description 6",
    color: "rgba(255, 159, 64, 0.8)",
    imagePath: "",
  },
  {
    id: "7",
    title: "Reggae",
    description: "Description 7",
    color: "rgba(199, 199, 199, 0.8)",
    imagePath: "",
  },
  {
    id: "8",
    title: "Blues",
    description: "Description 8",
    color: "rgba(83, 102, 255, 0.8)",
    imagePath: "",
  },
  {
    id: "9",
    title: "Country",
    description: "Description 9",
    color: "rgba(255, 99, 132, 0.8)",
    imagePath: "",
  },
  {
    id: "10",
    title: "Folk",
    description: "Description 10",
    color: "rgba(54, 162, 235, 0.8)",
    imagePath: "",
  },
  {
    id: "11",
    title: "Latin",
    description: "Description 11",
    color: "rgba(255, 206, 86, 0.8)",
    imagePath: "",
  },
  {
    id: "12",
    title: "Metal",
    description: "Description 12",
    color: "rgba(75, 192, 192, 0.8)",
    imagePath: "",
  },
  {
    id: "13",
    title: "R&B",
    description: "Description 13",
    color: "rgba(153, 102, 255, 0.8)",
    imagePath: "",
  },
  {
    id: "14",
    title: "Soul",
    description: "Description 14",
    color: "rgba(255, 159, 64, 0.8)",
    imagePath: "",
  },
  {
    id: "15",
    title: "Punk",
    description: "Description 15",
    color: "rgba(199, 199, 199, 0.8)",
    imagePath: "",
  },
  {
    id: "16",
    title: "Disco",
    description: "Description 16",
    color: "rgba(83, 102, 255, 0.8)",
    imagePath: "",
  },
  {
    id: "17",
    title: "Funk",
    description: "Description 17",
    color: "rgba(255, 99, 132, 0.8)",
    imagePath: "",
  },
  {
    id: "18",
    title: "Gospel",
    description: "Description 18",
    color: "rgba(54, 162, 235, 0.8)",
    imagePath: "",
  },
  {
    id: "19",
    title: "Opera",
    description: "Description 19",
    color: "rgba(255, 206, 86, 0.8)",
    imagePath: "",
  },
  {
    id: "20",
    title: "K-Pop",
    description: "Description 20",
    color: "rgba(75, 192, 192, 0.8)",
    imagePath: "",
  },
  {
    id: "21",
    title: "Ska",
    description: "Description 21",
    color: "rgba(153, 102, 255, 0.8)",
    imagePath: "",
  },
  {
    id: "22",
    title: "House",
    description: "Description 22",
    color: "rgba(255, 159, 64, 0.8)",
    imagePath: "",
  },
];

export const artists: IArtist[] = [
  {
    id: "1",
    name: "Ed Sheeran",
    slug: "Ed-Sheeran",
    imagePath: "",
    followers: 12000000,
    songs: 0,
    playlists: 0,
    roleId: "1",
    role: {
      id: "1",
      name: "Not user",
    },
  },
  {
    id: "2",
    name: "The Weeknd",
    slug: "The-Weeknd",
    imagePath: undefined,
    followers: 15000000,
    songs: 0,
    playlists: 0,
    roleId: "1",
    role: {
      id: "1",
      name: "Not user",
    },
  },
  {
    id: "3",
    name: "Dua Lipa",
    slug: "Dua-Lipa",
    imagePath: "",
    followers: 8000000,
    songs: 0,
    playlists: 0,
    roleId: "1",
    role: {
      id: "1",
      name: "Not user",
    },
  },
  {
    id: "4",
    name: "Billie Eilish",
    slug: "Billie-Eilish",
    imagePath: undefined,
    followers: 10000000,
    songs: 0,
    playlists: 0,
    roleId: "1",
    role: {
      id: "1",
      name: "Not user",
    },
  },
  {
    id: "5",
    name: "Lil Nas X",
    slug: "Lil-Nas-X",
    imagePath: "",
    followers: 7000000,
    songs: 0,
    playlists: 0,
    roleId: "1",
    role: {
      id: "1",
      name: "Not user",
    },
  },
  {
    id: "6",
    name: "Adele",
    slug: "Adele-",
    imagePath: "",
    followers: 20000000,
    songs: 0,
    playlists: 0,
    roleId: "1",
    role: {
      id: "1",
      name: "Not user",
    },
  },
  {
    id: "7",
    name: "Mark Ronson",
    slug: "Mark-Ronson",
    imagePath: "",
    followers: 5000000,
    songs: 0,
    playlists: 0,
    roleId: "1",
    role: {
      id: "1",
      name: "Not user",
    },
  },
  {
    id: "8",
    name: "Bruno Mars",
    slug: "Bruno- Mars",
    imagePath: "",
    followers: 18000000,
    songs: 0,
    playlists: 0,
    roleId: "1",
    role: {
      id: "1",
      name: "Not user",
    },
  },
  {
    id: "9",
    name: "Camila Cabello",
    slug: "Camila-Cabello",
    imagePath: "",
    followers: 9000000,
    songs: 0,
    playlists: 0,
    roleId: "1",
    role: {
      id: "1",
      name: "Not user",
    },
  },
  {
    id: "10",
    name: "Shawn Mendes",
    slug: "Shawn-Mendes",
    imagePath: "",
    followers: 11000000,
    songs: 0,
    playlists: 0,
    roleId: "1",
    role: {
      id: "1",
      name: "Not user",
    },
  },
  {
    id: "11",
    name: "Young Thug",
    slug: "Young- Thug",
    imagePath: "",
    followers: 6000000,
    songs: 0,
    playlists: 0,
    roleId: "1",
    role: {
      id: "1",
      name: "Not user",
    },
  },
];

export const exSong: ISong = {
  id: "id",
  title: "title",
  description: "description",
  imagePath: "",
  genre: genres[0],
  creator: artists[0],
  owner: [artists[0], artists[1]],
  createdAt: "2024-10-26 19:54:53",
  duration: "duration",
  public: true,
  number: 0,
  listens: 0,
  likes: 0,
  moods: [moods[12], moods[10]],
};

export const exArtist: IArtist = {
  id: "2",
  name: "Sơn Tùng MTP",
  imagePath: "",
  followers: 0,
  songs: 0,
  playlists: 0,
  roleId: "1",
  role: {
    id: "1",
    name: "Not user",
  },
};

export const exRoom: IRoom = {
  id: "1",
  title: "Room 1",
  description: "Description 1",
  creator: exArtist,
  membersCount: 0,
  songCount: 0,
  createAt: "2024-10-26 19:54:53",
};

export const songs: ISong[] = [
  {
    id: "1",
    title: "Shape of You",
    description: "A song by Ed Sheeran",
    imagePath: "",
    genre: genres[0],
    creator: artists[0],
    owner: [
      artists[0],
      artists[2],
      artists[4],
      artists[8],
      artists[5],
      artists[3],
    ],
    createdAt: "2024-10-26 19:54:53",
    duration: "3:53",
    public: true,
    number: 1,
    listens: 232,
    likes: 100,
    moods: [moods[0], moods[4], moods[5], moods[6], moods[7]],
  },
  {
    id: "2",
    title: "Blinding Lights",
    description: "A song by The Weeknd",
    imagePath: undefined,
    genre: genres[0],
    creator: artists[0],
    owner: [artists[2], artists[3]],
    createdAt: "2024-10-26 19:54:53",
    duration: "3:20",
    public: true,
    number: 2,
    listens: 34343,
    likes: 123,
    moods: [moods[1], moods[10]],
  },
  {
    id: "3",
    title: "Levitating",
    description: "A song by Dua Lipa",
    imagePath: "",
    genre: genres[0],
    creator: artists[0],
    owner: [artists[4], artists[5]],
    createdAt: "2024-10-26 19:54:53",
    duration: "3:23",
    public: true,
    number: 3,
    listens: 1500000,
    likes: 750000,
    moods: [moods[0], moods[7]],
  },
  {
    id: "4",
    title: "Bad Guy",
    description: "A song by Billie Eilish",
    imagePath: undefined,
    genre: genres[0],
    creator: artists[0],
    owner: [artists[6], artists[7]],
    createdAt: "2024-10-26 19:54:53",
    duration: "3:14",
    public: true,
    number: 4,
    listens: 1800000,
    likes: 900000,
    moods: [moods[2], moods[5]],
  },
  {
    id: "5",
    title: "Old Town Road",
    description: "A song by Lil Nas X",
    imagePath: "",
    genre: genres[0],
    creator: artists[0],
    owner: [artists[8], artists[9]],
    createdAt: "2024-10-26 19:54:53",
    duration: "2:37",
    public: true,
    number: 5,
    listens: 2500000,
    likes: 1200000,
    moods: [moods[3], moods[6]],
  },
  {
    id: "6",
    title: "Someone Like You",
    description: "A song by Adele",
    imagePath: "",
    genre: genres[0],
    creator: artists[0],
    owner: [artists[10], artists[9]],
    createdAt: "2024-10-26 19:54:53",
    duration: "4:45",
    public: true,
    number: 6,
    listens: 3000000,
    likes: 1500000,
    moods: [moods[1], moods[9]],
  },
  {
    id: "7",
    title: "Rolling in the Deep",
    description: "A song by Adele",
    imagePath: "",
    genre: genres[0],
    creator: artists[0],
    owner: [artists[10], artists[1]],
    createdAt: "2024-10-26 19:54:53",
    duration: "3:48",
    public: true,
    number: 7,
    listens: 3500000,
    likes: 1750000,
    moods: [moods[2], moods[8]],
  },
  {
    id: "8",
    title: "Uptown Funk",
    description: "A song by Mark Ronson ft. Bruno Mars",
    imagePath: "",
    genre: genres[0],
    creator: artists[0],
    owner: [artists[9], artists[10]],
    createdAt: "2024-10-26 19:54:53",
    duration: "4:30",
    public: true,
    number: 8,
    listens: 4000000,
    likes: 2000000,
    moods: [moods[0], moods[6]],
  },
  {
    id: "9",
    title: "Havana",
    description: "A song by Camila Cabello ft. Young Thug",
    imagePath: "",
    genre: genres[0],
    creator: artists[0],
    owner: [artists[6], artists[7]],
    createdAt: "2024-10-26 19:54:53",
    duration: "3:37",
    public: true,
    number: 9,
    listens: 4500000,
    likes: 2250000,
    moods: [moods[3], moods[5]],
  },
  {
    id: "10",
    title: "Senorita",
    description: "A song by Shawn Mendes & Camila Cabello",
    imagePath: "",
    genre: genres[0],
    creator: artists[0],
    owner: [artists[2], artists[3]],
    createdAt: "2024-10-26 19:54:53",
    duration: "3:11",
    public: true,
    number: 10,
    listens: 5000000,
    likes: 2500000,
    moods: [moods[4], moods[7]],
  },
];

export const playlists: IPlaylist[] = [
  {
    id: "1",
    title: "Playlist 1",
    description: "Description 1",
    imagePath: "",
    genre: genres[0],
    creator: artists[0],
    createdAt: "2024-10-26 19:54:53",
    public: true,
    total: 0,
    likes: 0,
    songsCount: 0,
    moods: [moods[12], moods[10]],
  },
  {
    id: "2",
    title: "Playlist 2",
    description: "Description 2",
    imagePath: "",
    genre: genres[0],
    creator: artists[0],
    createdAt: "2024-10-26 19:54:53",
    public: true,
    total: 0,
    likes: 0,
    songsCount: 0,
    moods: [moods[12], moods[10]],
  },
  {
    id: "3",
    title: "Playlist 3",
    description: "Description 3",
    imagePath: "",
    genre: genres[0],
    creator: artists[0],
    createdAt: "2024-10-26 19:54:53",
    public: true,
    total: 0,
    likes: 0,
    songsCount: 0,
    moods: [moods[12], moods[10]],
  },
  {
    id: "4",
    title: "Playlist 4",
    description: "Description 4",
    imagePath: "",
    genre: genres[0],
    creator: artists[0],
    createdAt: "2024-10-26 19:54:53",
    public: true,
    total: 0,
    likes: 0,
    songsCount: 0,
    moods: [moods[12], moods[10]],
  },
  {
    id: "5",
    title: "Playlist 5",
    description: "Description 5",
    imagePath: "",
    genre: genres[0],
    creator: artists[0],
    createdAt: "2024-10-26 19:54:53",
    public: true,
    total: 0,
    likes: 0,
    songsCount: 0,
    moods: [moods[12], moods[10]],
  },
  {
    id: "6",
    title: "Playlist 6",
    description: "Description 6",
    imagePath: "",
    genre: genres[0],
    creator: artists[0],
    createdAt: "2024-10-26 19:54:53",
    public: true,
    total: 0,
    likes: 0,
    songsCount: 0,
    moods: [moods[12], moods[10]],
  },
  {
    id: "7",
    title: "Playlist 7",
    description: "Description 7",
    imagePath: "",
    genre: genres[0],
    creator: artists[0],
    createdAt: "2024-10-26 19:54:53",
    public: true,
    total: 0,
    likes: 0,
    songsCount: 0,
    moods: [moods[12], moods[10]],
  },
  {
    id: "8",
    title: "Playlist 8",
    description: "Description 8",
    imagePath: "",
    genre: genres[0],
    creator: artists[0],
    createdAt: "2024-10-26 19:54:53",
    public: true,
    total: 0,
    likes: 0,
    songsCount: 0,
    moods: [moods[12], moods[10]],
  },
  {
    id: "9",
    title: "Playlist 9",
    description: "Description 9",
    imagePath: "",
    genre: genres[0],
    creator: artists[0],
    createdAt: "2024-10-26 19:54:53",
    public: true,
    total: 0,
    likes: 0,
    songsCount: 0,
    moods: [moods[12], moods[10]],
  },
  {
    id: "10",
    title: "Playlist 10",
    description: "Description 10",
    imagePath: "",
    genre: genres[0],
    creator: artists[0],
    createdAt: "2024-10-26 19:54:53",
    public: true,
    total: 0,
    likes: 0,
    songsCount: 0,
    moods: [moods[12], moods[10]],
  },
  {
    id: "11",
    title: "Playlist 11",
    description: "Description 11",
    imagePath: "",
    genre: genres[0],
    creator: artists[0],
    createdAt: "2024-10-26 19:54:53",
    public: true,
    total: 0,
    likes: 0,
    songsCount: 0,
    moods: [moods[12], moods[10]],
  },
  {
    id: "12",
    title: "Playlist 12",
    description: "Description 12",
    imagePath: "",
    genre: genres[0],
    creator: artists[0],
    createdAt: "2024-10-26 19:54:53",
    public: true,
    total: 0,
    likes: 0,
    songsCount: 0,
    moods: [moods[12], moods[10]],
  },
  {
    id: "13",
    title: "Playlist 13",
    description: "Description 13",
    imagePath: "",
    genre: genres[0],
    creator: artists[0],
    createdAt: "2024-10-26 19:54:53",
    public: true,
    total: 0,
    likes: 0,
    songsCount: 0,
    moods: [moods[12], moods[10]],
  },
  {
    id: "14",
    title: "Playlist 14",
    description: "Description 14",
    imagePath: "",
    genre: genres[0],
    creator: artists[0],
    createdAt: "2024-10-26 19:54:53",
    public: true,
    total: 0,
    likes: 0,
    songsCount: 0,
    moods: [moods[12], moods[10]],
  },
];

export const lyrics = [
  {
    id: 1,
    time: "00:00",
    text: "Em của ngày hôm qua",
  },
  {
    id: 2,
    time: "00:10",
    text: "Đã xa rồi, đã xa rồi",
  },
  {
    id: 3,
    time: "00:20",
    text: "Những kỷ niệm, những kỷ niệm",
  },
  {
    id: 4,
    time: "00:30",
    text: "Còn đâu nữa, còn đâu nữa",
  },
  {
    id: 5,
    time: "00:40",
    text: "Những lời hứa, những lời hứa",
  },
  {
    id: 6,
    time: "00:50",
    text: "Giờ chỉ là, giờ chỉ là",
  },
  {
    id: 7,
    time: "01:00",
    text: "Những giấc mơ, những giấc mơ",
  },
  {
    id: 8,
    time: "01:10",
    text: "Em của ngày hôm qua",
  },
  {
    id: 9,
    time: "01:20",
    text: "Đã xa rồi, đã xa rồi",
  },
  {
    id: 10,
    time: "01:30",
    text: "Những kỷ niệm, những kỷ niệm",
  },
  {
    id: 11,
    time: "01:40",
    text: "Còn đâu nữa, còn đâu nữa",
  },
  {
    id: 12,
    time: "01:50",
    text: "Những lời hứa, những lời hứa",
  },
  {
    id: 13,
    time: "02:00",
    text: "Giờ chỉ là, giờ chỉ là",
  },
  {
    id: 14,
    time: "02:10",
    text: "Những giấc mơ, những giấc mơ",
  },
  {
    id: 15,
    time: "02:20",
    text: "Em của ngày hôm qua",
  },
  {
    id: 16,
    time: "02:30",
    text: "Đã xa rồi, đã xa rồi",
  },
  {
    id: 17,
    time: "02:40",
    text: "Những kỷ niệm, những kỷ niệm",
  },
  {
    id: 18,
    time: "02:50",
    text: "Còn đâu nữa, còn đâu nữa",
  },
  {
    id: 19,
    time: "03:00",
    text: "Những lời hứa, những lời hứa",
  },
  {
    id: 20,
    time: "03:10",
    text: "Giờ chỉ là, giờ chỉ là",
  },
  {
    id: 21,
    time: "03:20",
    text: "Những giấc mơ, những giấc mơ",
  },
];

export const comments: IMessageChat[] = [
  {
    id: "1",
    roomId: "1",
    userId: "1",
    content: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    user: exArtist,
    room: exRoom,
    createAt: new Date(),
  },
  {
    id: "1",
    roomId: "1",
    userId: "1",
    content: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    user: exArtist,
    room: exRoom,
    createAt: new Date(),
  },
  {
    id: "1",
    roomId: "1",
    userId: "3",
    content:
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
    room: exRoom,
    user: exArtist,
    createAt: new Date(),
  },
  {
    id: "1",
    roomId: "1",
    userId: "4",
    content:
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum.",
    room: exRoom,
    user: exArtist,
    createAt: new Date(),
  },
  {
    id: "1",
    roomId: "1",
    userId: "5",
    content:
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia.",
    room: exRoom,
    user: exArtist,
    createAt: new Date(),
  },
  {
    id: "1",
    roomId: "1",
    userId: "6",
    content: "Deserunt mollit anim id est laborum.",
    room: exRoom,
    user: exArtist,
    createAt: new Date(),
  },
  {
    id: "1",
    roomId: "1",
    userId: "7",
    content: "Curabitur pretium tincidunt lacus. Nulla gravida orci a odio.",
    room: exRoom,
    user: exArtist,
    createAt: new Date(),
  },
  {
    id: "1",
    roomId: "1",
    userId: "8",
    content:
      "Nullam varius, turpis et commodo pharetra, est eros bibendum elit.",
    room: exRoom,
    user: exArtist,
    createAt: new Date(),
  },
  {
    id: "1",
    roomId: "1",
    userId: "9",
    content:
      "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices.",
    room: exRoom,
    user: exArtist,
    createAt: new Date(),
  },
  {
    id: "1",
    roomId: "1",
    userId: "10",
    content: "In hac habitasse platea dictumst. Fusce euismod consequat ante.",
    room: exRoom,
    user: exArtist,
    createAt: new Date(),
  },
  {
    id: "1",
    roomId: "1",
    userId: "11",
    content: "In hac habitasse platea dictumst. Fusce euismod consequat ante.",
    room: exRoom,
    user: exArtist,
    createAt: new Date(),
  },
  {
    id: "1",
    roomId: "1",
    userId: "12",
    content: "In hac habitasse platea dictumst. Fusce euismod consequat ante.",
    room: exRoom,
    user: exArtist,
    createAt: new Date(),
  },
  {
    id: "1",
    roomId: "1",
    userId: "13",
    content: "Maecenas malesuada elit lectus felis, malesuada ultricies.",
    room: exRoom,
    user: exArtist,
    createAt: new Date(),
  },
];

export const exFavorites: IPlaylist = {
  id: "1",
  title: "Favorites",
  description: "",
  imagePath: "",
  genre: genres[0],
  creator: artists[0],
  public: true,
  total: 0,
  likes: 0,
  songsCount: 0,
  createdAt: new Date().toISOString(),
};
